name: Lint Code

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Get list of changed files
        id: changed_files
        run: |
          git diff --name-only HEAD~1 HEAD > changed_files.txt        
          grep -E '\.js$|\.jsx$|\.ts$|\.tsx$' changed_files.txt > lint_files.txt || true
        
      - name: Run ESLint on changed files
        run: |
          if [ -s lint_files.txt ]; then
            npx eslint --fix $(cat lint_files.txt)
          else
            echo "No files changed."
          fi