name: Run Unit Tests

on: 
  pull_request:
    branches: ['main', 'dev'] 
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo systemctl start docker
        sudo systemctl enable docker
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Set up Docker Compose
      env:
        COOKIE_SECRET: 2114e2420e79aa59430810f3b01434784721859ce93b7629eb1cba4144045344
        JWT_SECRET: 2114e2420e79aa59431810f3b01434784721859sd93b7629eb1dba4144045347
        JWT_EXPIRY: 86400000
        COOKIE_NAME: time-tracking-system
        PORT: 8000
        CLIENT_PORT: 9000
        EMAIL: rakibattaridib@gmail.com
        KEY: vkcobgfzfcdmjpqt
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: ubuntu
        MYSQL_PASSWORD: 123456
        MYSQL_PORT: 3306
        MYSQL_HOST: localhost
      run: docker-compose up -d database

    - name: Wait for the database to be ready
      run: |
        until docker-compose exec -T database mysqladmin ping --silent; do
          echo "Waiting for the database connection..."
          sleep 5
        done
    
    - name: Run Unit Tests
      run: npm test
